{% set name = "gqrx" %}
{% set version = "2.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gqrx-sdr/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7bb7e6a490d7d4669a4d1596ad52f5af08e7167d78117b3d1fd711a368536855
  patches:
    - 0001-Don-t-build-a-resource-file-for-the-executable-on-Wi.patch  # [win]
    - 0002-Don-t-build-a-win32-app-instead-of-a-console-app.patch  # [win]

build:
  number: 2
  ignore_run_exports_from:
    # see below, workaround involving adding python to host
    - python  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config  # [not win]
    # cross-compilation requirements
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - gnuradio-core  # [not gnuradio_extra_pin]
    - gnuradio-core {{ gnuradio_extra_pin }}.*  # [gnuradio_extra_pin]
    - gnuradio-osmosdr
    - libboost-headers
    - pybind11
    - pulseaudio  # [linux]
    - qt-main
    - volk
    # need python in host for cross-compilation so cross-python will work
    - python  # [build_platform != target_platform]
  run:
    # need python in run so linter doesn't complain b/c also in host
    - python  # [build_platform != target_platform]

test:
  requires:
    - coreutils  # [not win]
  commands:
    - test -f $PREFIX/bin/gqrx  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\gqrx.exe exit 1  # [win]
    - xvfb-run -a -s "-screen 0 1024x768x24" bash -c 'timeout --preserve-status 10 gqrx -r || [[ $? -eq 143 ]]'  # [linux and x86_64]
    - timeout --preserve-status 10 gqrx -r || [[ $? -eq 143 ]]  # [not linux and not win]
    - start gqrx -r && ping -n 30 127.0.0.1 >nul && taskkill /im gqrx.exe /f  # [win]

app:
  entry: gqrx --edit
  icon: gqrx-icon.png
  summary: gqrx
  type: desk

about:
  home: https://gqrx.dk/
  license: GPL-3.0-or-later AND Apache-2.0
  license_family: GPL
  license_file:
    - COPYING
    - LICENSE-CTK
  summary: Software defined radio receiver powered by GNU Radio and Qt
  description: |
    Gqrx is an open source software defined radio (SDR) receiver implemented using GNU
    Radio and the Qt GUI toolkit. Currently it works on Linux and Mac with hardware
    supported by gr-osmosdr, including Funcube Dongle, RTL-SDR, Airspy, HackRF,
    BladeRF, RFSpace, USRP and SoapySDR.

    Gqrx can operate as an AM/FM/SSB receiver with audio output or as an FFT-only
    instrument. There are also various hooks for interacting with external application
    using network sockets.
  dev_url: https://github.com/gqrx-sdr/gqrx

extra:
  recipe-maintainers:
    - ryanvolz
