{% set name = "gqrx" %}
{% set version = "2.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gqrx-sdr/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c4fc85e6aec257e56e0c2963c5c2f7aa210a8b6df73f7cb4e398ec2f1c9e1d33
  patches:
    - 0001-Don-t-build-a-resource-file-for-the-executable-on-Wi.patch  # [win]
    - 0002-Don-t-build-a-win32-app-instead-of-a-console-app.patch  # [win]
    - 0003-Increase-zero-file-size-so-empty-receive-source-work.patch  # [win]

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config  # [not win]
   # libudev needed to link against libusb (through gnuradio-osmosdr) on linux
    - {{ cdt('libudev') }}  # [linux]
   # below are needed to link with Qt for qtgui
    - {{ cdt('libice') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libsm') }}  # [linux]
    - {{ cdt('libx11') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libuuid') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    # boost needed for a few headers separately from gnuradio dep
    - boost-cpp
    - gnuradio-core
    - gnuradio-osmosdr
    # needed while on cos6 sysroot, make sure we get cos6-compatible libusb
    # (this does not add a run_exports for libusb)
    - libusb-cos6  # [linux]
    - pulseaudio  # [linux]
    - qt
    - volk
    # pulled in by gnuradio-core and linked against, so include explicitly
    - log4cpp
  run:
    # pulled in by gnuradio-core and linked against, so include explicitly
    - log4cpp

test:
  commands:
    # can't test whether it runs because a display is needed
    - test -f $PREFIX/bin/gqrx  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\gqrx.exe exit 1  # [win]

app:
  entry: gqrx --edit
  icon: gqrx-icon.png
  summary: Gqrx
  type: desk

about:
  home: https://gqrx.dk/
  license: GPL-3.0-or-later AND Apache-2.0
  license_family: GPL
  license_file:
    - COPYING
    - LICENSE-CTK
  summary: Software defined radio receiver powered by GNU Radio and Qt
  description: |
    Gqrx is an open source software defined radio (SDR) receiver implemented using GNU
    Radio and the Qt GUI toolkit. Currently it works on Linux and Mac with hardware
    supported by gr-osmosdr, including Funcube Dongle, RTL-SDR, Airspy, HackRF,
    BladeRF, RFSpace, USRP and SoapySDR.

    Gqrx can operate as an AM/FM/SSB receiver with audio output or as an FFT-only
    instrument. There are also various hooks for interacting with external application
    using network sockets.
  dev_url: https://github.com/gqrx-sdr/gqrx

extra:
  recipe-maintainers:
    - ryanvolz
