conda_forge_output_validation: true
bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
test: native_and_emulated
